#!/bin/bash
set -e

[ ! -r /etc/default/mnt-disk ] && exit 1

. /etc/default/mnt-disk

disks_list=""
partitions_list=""
partitions_count=0
oldIFS=$IFS
IFS=','
for disk in $DISKS; do
    disks_list="$disks_list $disk"
    partitions_list="$partitions_list ${disk}1"
    partitions_count=$((partitions_count + 1))
done
IFS=$oldIFS
disks_list=${disks_list## }
partitions_list=${partitions_list## }

#### removing LVM configuration items and replacing with non-LVM

for disk in ${disks_list}; do
  if [ ! -b "$disk" ]; then
    echo "Wiping disk(s) ${disks_list[*]} ..."
    wipefs -faq ${disks_list[*]}
  fi
 
  for disk in $disks_list; do
    echo "Partitioning disk $disk ..."
    parted --script "$disk" mklabel gpt
    parted --script --align optimal "$disk" mkpart primary $MOUNT_FSTYPE 2048s 100%
  done

  echo "Probing partitions ..."
  partprobe
  for delay in $(seq 1 4); do
    sleep $delay
    test -b "${disk}1" && break
  done

  echo "Formatting data partition ${partitions_list[*]} ..."
  sh -c "mkfs.$MOUNT_FSTYPE -F ${partitions_list[*]}"

done

echo "Creating resource mountpoint ..."
mkdir -p "$MOUNT_PATH"
