#!/bin/bash
set -e

[ ! -r /etc/default/mnt-disk ] && exit 1

. /etc/default/mnt-disk

disks_list=""
partitions_list=""
oldIFS=$IFS
IFS=','
for disk in $DISKS; do
    disks_list="$disks_list $disk"
    partitions_list="$partitions_list ${disk}1"
done
IFS=$oldIFS
disks_list=${disks_list## }
partitions_list=${partitions_list## }

if [ "$DESTROY_ON_STOP" -eq "1" ]; then

    echo "Unmounting ephemeral storage "$MOUNT_PATH" ..."
    umount "$MOUNT_PATH" || /bin/true

    echo "Removing partition from device ..."
    parted --script "$disk" rm 1 

    echo "Wiping disks ${disks_list[*]} ..."
    wipefs -faq ${disks_list[*]}
fi
